# 端口
server:
  port: 8080
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://192.168.10.250:3306/test?useSSL=false
    username: eqst
    password: eqst
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis配置
mybatis-plus:
  type-aliases-package: com.report.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
